### ISSUE TITLE
CopyVaspOutputs and scratch_dir

### ISSUE THREAD

**Issue by fraricci** [hackingmaterials/atomate#95] opened 2017-04-17 17:56 UTC
I am using atomate and its default workflows to produce this sequence:
Static -> Uniform -> Boltztrap

I set a scratch_dir in the fw_worker.yaml.
What I get is that in the directory where the uniform task stores the final results,
I have a vasprun.xml that correspond to the static task and a vasprun.xml.gz that 
is the result of the uniform calculation. I think that is due to use of a scratch_dir.
The problem is that the CopyVaspOutputs inside the Boltztrap firetask copies 
by default the vasprun.xml (static calculation) and not the vasprun.xml.gz (unifom one)
that is what I want but in general what it should be copied.

**Comment by computron** [comment] 2017-04-17 21:32
The @fraricci 

The contents of the scratch_dir should have been copied back to the main directory at the end of the job. Can you attach the contents of the main directory where the uniform run was executed and also the scratch directory contents (if you have it)?

**Comment by fraricci** [comment] 2017-04-18 07:56
Yes, I think it is what happens. But all the files are gzipped before so 
the previous files created in the main directory are not overwritten or deleted.
I don't have the tmp directory in scratch, but here is the list of files in the main directory:
POSCAR (input for uniform calc)
KPOINTS (input for uniform calc)
INCAR (input for uniform calc)
CHGCAR (same file of static calc)
vasprun.xml (same file of static calc)
OUTCAR (same file of static calc)
Cs2TeI6-_deformation-66979.out
task.json
XDATCAR.gz  (output for uniform calc)
vasprun.xml.gz 
POTCAR.orig.gz
POTCAR.gz
POSCAR.orig.gz
PCDAT.gz
OUTCAR.gz
KPOINTS.orig.gz
KPOINTS.gz
INCAR.orig.gz
INCAR.gz
FW_submit.script.gz
FW.json.gz
FW--Cs2TeI6-_deformation_1_uniform.gz
EIGENVAL.gz
Cs2TeI6-_deformation-66979.error.gz
CONTCAR.gz
CHG.gz
AECCAR2.gz
AECCAR1.gz
AECCAR0.gz
WAVECAR.gz
vasp.out.gz
std_err.txt.gz
REPORT.gz
PROCAR.gz
POSCAR.gz
OSZICAR.gz
LOCPOT.gz
DOSCAR.gz
custodian.json.gz
Cs2TeI6-_deformation-66979.out.gz
CHGCAR.gz
POTCAR 
FW.json
FW--Cs2TeI6-_deformation_1_uniform
Cs2TeI6-_deformation-66979.error
FW_submit.script

I think that the correct files are copied from static to the uniform main dir,
and the set of input files is generated from them. They are copied in the
scratch_dir, the calculation runs, and the GZIPPED output is copied back to 
main directory. It ends up that you have a mix of files from static and uniform
calculations and if you run a calc on top of the uniform one, the non-zipped
files are copied, instead of the correct zipped ones.
I think this is what happens.
I have not tried to run without setting scratch_dir, but I think in that case
it should work fine. In that case the new vasprun.xml overwrite the previous one.

**Comment by computron** [comment] 2017-04-18 18:17
@shyuep Can you comment on this? It is at least related to custodian / scratch dir behavior and the solution might require custodian changes.

Brief summary of events:
1. When running a uniform band structure, atomate copies files from the static run (INCAR, POSCAR (via CONTCAR), POTCAR, KPOINTS, OUTCAR, vasprun.xml, CHGCAR) to the run directory. These files are unzipped (if zipped) and used to help set up the uniform job inputs by reading and modifying the static run outputs. 
2. Next, the uniform band structure inputs are created. Thus in the directory we now have:
- INCAR (for uniform run), POSCAR (for uniform run), KPOINTS (for uniform run), POTCAR (for uniform run), OUTCAR (for *static* run), vasprun.xml (for *static* run), CHGCAR (for *static* run). The last three are particularly important in this error.
3. Now that we have this directory set up, if we run custodian in the current directory there is no problem. The static run's CHGCAR, OUTCAR, and vasprun.xml are overwritten.
4. However, if we run custodian in this directory with scratch_dir and with zipped outputs, we have a problem. VASP runs in a scratch dir, all the files are zipped, and copied back. We now end up with the files list that Francesco mentioned. However, we have some duplicates - i.e., OUTCAR and OUTCAR.gz, with the former being from the static run and the latter from the uniform run. This causes downstream problems...

If it were just the vasprun.xml and OUTCAR, I would say to just fix this in atomate. e.g., after creating the inputs for the uniform run, clean the directory of any VASP output files in that directory. For implementation, we can either incorporate this as a step in existing FireTasks that write input files, or we can create a new FireTask that does this and should be run before custodian.

However, the CHGCAR makes things more tricky. I can't just delete the CHGCAR before running custodian because I need it for VASP. If I run custodian with a previous CHGCAR in that directory as a starting point with scratch_dir=True and gzip=True, then I end up with a directory that has both CHGCAR and CHGCAR.gz, with the former being the "old" calc and the latter being the "new" calc. This issue has nothing to do with atomate and would somehow need to be fixed in custodian or even monty. For example, when copying back the scratch directory back to the original directory, one might remove all the contents of the original directory (seems a bit unsafe...just one suggestion and certainly not a good default option) and then replace with the contents of the scratch directory. i.e., instead of the final directory being a union of the files in that were in the original directory and the scratch directory final outputs, the final directory state is the state of the scratch directory.

**Comment by computron** [comment] 2017-04-28 20:55
@shyuep any thoughts? Reminder: the root of the issue is that when you use the scratch_dir functionality in monty, the final contents of your original directory aren't the same as the final contents of the scratch_dir. Instead, the final contents of your original directory are the union of files from both - which is especially problematic if the last step in your scratch_dir operation is to gzip things whereas things started off not gzipped.

**Comment by computron** [comment] 2017-04-28 21:01
I also opened a ticket in "monty" about this

**Comment by computron** [comment] 2017-04-28 22:37
@fraricci - a recent commit to monty should fix this issue. If you use the bleeding edge version of all the codes it should already work now. Otherwise it will work after there is a new release of monty such that atomate can update its requirements. I will close this ticket once that latter case is finalized, but let me know if you still see problems after that.

Thanks again for reporting this -

**Comment by fraricci** [comment] 2017-04-29 20:41
Thank you to deal with it.
I already hacked my version to solve the problem. But I'll try the new
version and​ let you know if there're other issues​.

**Comment by computron** [comment] 2017-05-30 16:42
I am closing this issue via monty 0.9.8

**Closed by computron** 2017-05-30 16:42 UTC
