### ISSUE TITLE
Magmom from previous run

### ISSUE THREAD

**Issue by fraricci** [hackingmaterials/atomate#275] opened 2019-03-17 10:58 UTC
What pointed out here:
https://github.com/hackingmaterials/atomate/blob/a2cfee5c7cad28e43b2756a4168959a92f4494dc/atomate/vasp/firetasks/write_inputs.py#L341

it might be solved now in:
https://github.com/materialsproject/pymatgen/issues/1397

**Comment by fraricci** [comment] 2019-03-17 10:59
I think that now magmom can be an optional external parameter.

**Comment by mkhorton** [comment] 2019-03-17 16:00
Yes, the optional `magnum` parameter is a result of inheriting from DictSet.

**Comment by itsshawnzhang** [comment] 2022-02-08 23:59
Since the problem is resolved, I will close this issue for now. Please let us know for any problems or concerns. Cheers! :)

**Closed by itsshawnzhang** 2022-02-08 23:59 UTC
